# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_accounts_add_cond_resp_association_condition_association_grpjobs import V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs

class TestV0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs(unittest.TestCase):
    """V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs:
        """Test V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs`
        """
        model = V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs()
        if include_optional:
            return V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs(
                infinite = True,
                number = 56,
                set = True
            )
        else:
            return V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs(
        )
        """

    def testV0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs(self):
        """Test V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrpjobs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
