# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_assocs_resp_associations_inner_accounting_inner import V0041OpenapiAssocsRespAssociationsInnerAccountingInner

class TestV0041OpenapiAssocsRespAssociationsInnerAccountingInner(unittest.TestCase):
    """V0041OpenapiAssocsRespAssociationsInnerAccountingInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsRespAssociationsInnerAccountingInner:
        """Test V0041OpenapiAssocsRespAssociationsInnerAccountingInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsRespAssociationsInnerAccountingInner`
        """
        model = V0041OpenapiAssocsRespAssociationsInnerAccountingInner()
        if include_optional:
            return V0041OpenapiAssocsRespAssociationsInnerAccountingInner(
                tres = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_tres.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_TRES(
                    count = 56, 
                    id = 56, 
                    name = '', 
                    type = '', ),
                allocated = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated(
                    seconds = 56, ),
                id = 56,
                start = 56
            )
        else:
            return V0041OpenapiAssocsRespAssociationsInnerAccountingInner(
        )
        """

    def testV0041OpenapiAssocsRespAssociationsInnerAccountingInner(self):
        """Test V0041OpenapiAssocsRespAssociationsInnerAccountingInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
