# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_job_info_resp import V0041OpenapiJobInfoResp

class TestV0041OpenapiJobInfoResp(unittest.TestCase):
    """V0041OpenapiJobInfoResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoResp:
        """Test V0041OpenapiJobInfoResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoResp`
        """
        model = V0041OpenapiJobInfoResp()
        if include_optional:
            return V0041OpenapiJobInfoResp(
                errors = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_errors_inner.v0_0_41_openapi_accounts_add_cond_resp_errors_inner(
                        description = '', 
                        error = '', 
                        error_number = 56, 
                        source = '', )
                    ],
                jobs = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner.v0_0_41_openapi_job_info_resp_jobs_inner(
                        account = '', 
                        accrue_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_accrue_time.v0_0_41_openapi_job_info_resp_jobs_inner_accrue_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        admin_comment = '', 
                        allocating_node = '', 
                        array_job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_job_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_job_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        array_max_tasks = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_max_tasks.v0_0_41_openapi_job_info_resp_jobs_inner_array_max_tasks(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        array_task_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        array_task_string = '', 
                        association_id = 56, 
                        batch_features = '', 
                        batch_flag = True, 
                        batch_host = '', 
                        billable_tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_billable_tres.v0_0_41_openapi_job_info_resp_jobs_inner_billable_tres(
                            infinite = True, 
                            number = 1.337, 
                            set = True, ), 
                        burst_buffer = '', 
                        burst_buffer_state = '', 
                        cluster = '', 
                        cluster_features = '', 
                        command = '', 
                        comment = '', 
                        container = '', 
                        container_id = '', 
                        contiguous = True, 
                        core_spec = 56, 
                        cores_per_socket = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cores_per_socket.v0_0_41_openapi_job_info_resp_jobs_inner_cores_per_socket(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpu_frequency_governor = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_governor.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_governor(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpu_frequency_maximum = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpu_frequency_minimum = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpus = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_cpus(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpus_per_task = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpus_per_task.v0_0_41_openapi_job_info_resp_jobs_inner_cpus_per_task(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpus_per_tres = '', 
                        cron = '', 
                        current_working_directory = '', 
                        deadline = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_deadline.v0_0_41_openapi_job_info_resp_jobs_inner_deadline(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        delay_boot = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_delay_boot.v0_0_41_openapi_job_info_resp_jobs_inner_delay_boot(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        dependency = '', 
                        derived_exit_code = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code(
                            return_code = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            signal = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                                id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                name = '', ), 
                            status = [
                                'INVALID'
                                ], ), 
                        eligible_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_eligible_time.v0_0_41_openapi_job_info_resp_jobs_inner_eligible_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        end_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_end_time.v0_0_41_openapi_job_info_resp_jobs_inner_end_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        excluded_nodes = '', 
                        exclusive = [
                            'true'
                            ], 
                        exit_code = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_exit_code(), 
                        extra = '', 
                        failed_node = '', 
                        features = '', 
                        federation_origin = '', 
                        federation_siblings_active = '', 
                        federation_siblings_viable = '', 
                        flags = [
                            'KILL_INVALID_DEPENDENCY'
                            ], 
                        gres_detail = [
                            ''
                            ], 
                        group_id = 56, 
                        group_name = '', 
                        het_job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_id.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        het_job_id_set = '', 
                        het_job_offset = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        hold = True, 
                        job_id = 56, 
                        job_resources = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(
                            cpus = 56, 
                            nodes = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(
                                allocation = [
                                    slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner(
                                        index = 56, 
                                        memory = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(
                                            allocated = 56, 
                                            used = 56, ), 
                                        name = '', 
                                        sockets = [
                                            slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner(
                                                cores = [
                                                    slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner(
                                                        index = 56, 
                                                        status = [
                                                            'INVALID'
                                                            ], )
                                                    ], 
                                                index = 56, )
                                            ], )
                                    ], 
                                count = 56, 
                                list = '', 
                                select_type = [
                                    'AVAILABLE'
                                    ], 
                                whole = True, ), 
                            select_type = [
                                'CPU'
                                ], 
                            threads_per_core = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        job_size_str = [
                            ''
                            ], 
                        job_state = [
                            'PENDING'
                            ], 
                        last_sched_evaluation = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_last_sched_evaluation.v0_0_41_openapi_job_info_resp_jobs_inner_last_sched_evaluation(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        licenses = '', 
                        mail_type = [
                            'BEGIN'
                            ], 
                        mail_user = '', 
                        max_cpus = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_max_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_max_cpus(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        max_nodes = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_max_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_max_nodes(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        maximum_switch_wait_time = 56, 
                        mcs_label = '', 
                        memory_per_cpu = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        memory_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        memory_per_tres = '', 
                        minimum_cpus_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        minimum_switches = 56, 
                        minimum_tmp_disk_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        name = '', 
                        network = '', 
                        nice = 56, 
                        node_count = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_node_count.v0_0_41_openapi_job_info_resp_jobs_inner_node_count(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        nodes = '', 
                        oversubscribe = True, 
                        partition = '', 
                        power = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_power.v0_0_41_openapi_job_info_resp_jobs_inner_power(), 
                        pre_sus_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_pre_sus_time.v0_0_41_openapi_job_info_resp_jobs_inner_pre_sus_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        preempt_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_preempt_time.v0_0_41_openapi_job_info_resp_jobs_inner_preempt_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        preemptable_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_preemptable_time.v0_0_41_openapi_job_info_resp_jobs_inner_preemptable_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        prefer = '', 
                        priority = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_priority.v0_0_41_job_desc_msg_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        profile = [
                            'NOT_SET'
                            ], 
                        qos = '', 
                        reboot = True, 
                        requeue = True, 
                        required_nodes = '', 
                        resize_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_resize_time.v0_0_41_openapi_job_info_resp_jobs_inner_resize_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        restart_cnt = 56, 
                        resv_name = '', 
                        scheduled_nodes = '', 
                        selinux_context = '', 
                        shared = [
                            'none'
                            ], 
                        show_flags = [
                            'ALL'
                            ], 
                        sockets_per_board = 56, 
                        sockets_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_sockets_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_sockets_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        standard_error = '', 
                        standard_input = '', 
                        standard_output = '', 
                        start_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_start_time.v0_0_41_openapi_job_info_resp_jobs_inner_start_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        state_description = '', 
                        state_reason = '', 
                        submit_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_submit_time.v0_0_41_openapi_job_info_resp_jobs_inner_submit_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        suspend_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_suspend_time.v0_0_41_openapi_job_info_resp_jobs_inner_suspend_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        system_comment = '', 
                        tasks = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks.v0_0_41_openapi_job_info_resp_jobs_inner_tasks(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_board = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_board.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_board(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_core = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_core(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_socket = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_socket.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_socket(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_tres.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_tres(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        thread_spec = 56, 
                        threads_per_core = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_threads_per_core(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        time_limit = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        time_minimum = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_time_minimum.v0_0_41_job_desc_msg_time_minimum(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tres_alloc_str = '', 
                        tres_bind = '', 
                        tres_freq = '', 
                        tres_per_job = '', 
                        tres_per_node = '', 
                        tres_per_socket = '', 
                        tres_per_task = '', 
                        tres_req_str = '', 
                        user_id = 56, 
                        user_name = '', 
                        wckey = '', )
                    ],
                last_backfill = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_last_backfill.v0_0_41_openapi_job_info_resp_last_backfill(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                last_update = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_last_update.v0_0_41_openapi_job_info_resp_last_update(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                meta = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta.v0_0_41_openapi_accounts_add_cond_resp_meta(
                    client = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_client.v0_0_41_openapi_accounts_add_cond_resp_meta_client(
                        group = '', 
                        source = '', 
                        user = '', ), 
                    command = [
                        ''
                        ], 
                    plugin = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin(
                        accounting_storage = '', 
                        data_parser = '', 
                        name = '', 
                        type = '', ), 
                    slurm = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm(
                        cluster = '', 
                        release = '', 
                        version = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), ), ),
                warnings = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiJobInfoResp(
                jobs = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner.v0_0_41_openapi_job_info_resp_jobs_inner(
                        account = '', 
                        accrue_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_accrue_time.v0_0_41_openapi_job_info_resp_jobs_inner_accrue_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        admin_comment = '', 
                        allocating_node = '', 
                        array_job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_job_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_job_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        array_max_tasks = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_max_tasks.v0_0_41_openapi_job_info_resp_jobs_inner_array_max_tasks(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        array_task_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        array_task_string = '', 
                        association_id = 56, 
                        batch_features = '', 
                        batch_flag = True, 
                        batch_host = '', 
                        billable_tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_billable_tres.v0_0_41_openapi_job_info_resp_jobs_inner_billable_tres(
                            infinite = True, 
                            number = 1.337, 
                            set = True, ), 
                        burst_buffer = '', 
                        burst_buffer_state = '', 
                        cluster = '', 
                        cluster_features = '', 
                        command = '', 
                        comment = '', 
                        container = '', 
                        container_id = '', 
                        contiguous = True, 
                        core_spec = 56, 
                        cores_per_socket = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cores_per_socket.v0_0_41_openapi_job_info_resp_jobs_inner_cores_per_socket(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpu_frequency_governor = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_governor.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_governor(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpu_frequency_maximum = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpu_frequency_minimum = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpus = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_cpus(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpus_per_task = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpus_per_task.v0_0_41_openapi_job_info_resp_jobs_inner_cpus_per_task(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        cpus_per_tres = '', 
                        cron = '', 
                        current_working_directory = '', 
                        deadline = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_deadline.v0_0_41_openapi_job_info_resp_jobs_inner_deadline(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        delay_boot = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_delay_boot.v0_0_41_openapi_job_info_resp_jobs_inner_delay_boot(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        dependency = '', 
                        derived_exit_code = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code(
                            return_code = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            signal = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                                id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                name = '', ), 
                            status = [
                                'INVALID'
                                ], ), 
                        eligible_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_eligible_time.v0_0_41_openapi_job_info_resp_jobs_inner_eligible_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        end_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_end_time.v0_0_41_openapi_job_info_resp_jobs_inner_end_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        excluded_nodes = '', 
                        exclusive = [
                            'true'
                            ], 
                        exit_code = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_exit_code(), 
                        extra = '', 
                        failed_node = '', 
                        features = '', 
                        federation_origin = '', 
                        federation_siblings_active = '', 
                        federation_siblings_viable = '', 
                        flags = [
                            'KILL_INVALID_DEPENDENCY'
                            ], 
                        gres_detail = [
                            ''
                            ], 
                        group_id = 56, 
                        group_name = '', 
                        het_job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_id.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        het_job_id_set = '', 
                        het_job_offset = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        hold = True, 
                        job_id = 56, 
                        job_resources = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(
                            cpus = 56, 
                            nodes = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(
                                allocation = [
                                    slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner(
                                        index = 56, 
                                        memory = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(
                                            allocated = 56, 
                                            used = 56, ), 
                                        name = '', 
                                        sockets = [
                                            slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner(
                                                cores = [
                                                    slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner(
                                                        index = 56, 
                                                        status = [
                                                            'INVALID'
                                                            ], )
                                                    ], 
                                                index = 56, )
                                            ], )
                                    ], 
                                count = 56, 
                                list = '', 
                                select_type = [
                                    'AVAILABLE'
                                    ], 
                                whole = True, ), 
                            select_type = [
                                'CPU'
                                ], 
                            threads_per_core = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        job_size_str = [
                            ''
                            ], 
                        job_state = [
                            'PENDING'
                            ], 
                        last_sched_evaluation = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_last_sched_evaluation.v0_0_41_openapi_job_info_resp_jobs_inner_last_sched_evaluation(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        licenses = '', 
                        mail_type = [
                            'BEGIN'
                            ], 
                        mail_user = '', 
                        max_cpus = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_max_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_max_cpus(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        max_nodes = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_max_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_max_nodes(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        maximum_switch_wait_time = 56, 
                        mcs_label = '', 
                        memory_per_cpu = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        memory_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        memory_per_tres = '', 
                        minimum_cpus_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        minimum_switches = 56, 
                        minimum_tmp_disk_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        name = '', 
                        network = '', 
                        nice = 56, 
                        node_count = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_node_count.v0_0_41_openapi_job_info_resp_jobs_inner_node_count(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        nodes = '', 
                        oversubscribe = True, 
                        partition = '', 
                        power = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_power.v0_0_41_openapi_job_info_resp_jobs_inner_power(), 
                        pre_sus_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_pre_sus_time.v0_0_41_openapi_job_info_resp_jobs_inner_pre_sus_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        preempt_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_preempt_time.v0_0_41_openapi_job_info_resp_jobs_inner_preempt_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        preemptable_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_preemptable_time.v0_0_41_openapi_job_info_resp_jobs_inner_preemptable_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        prefer = '', 
                        priority = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_priority.v0_0_41_job_desc_msg_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        profile = [
                            'NOT_SET'
                            ], 
                        qos = '', 
                        reboot = True, 
                        requeue = True, 
                        required_nodes = '', 
                        resize_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_resize_time.v0_0_41_openapi_job_info_resp_jobs_inner_resize_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        restart_cnt = 56, 
                        resv_name = '', 
                        scheduled_nodes = '', 
                        selinux_context = '', 
                        shared = [
                            'none'
                            ], 
                        show_flags = [
                            'ALL'
                            ], 
                        sockets_per_board = 56, 
                        sockets_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_sockets_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_sockets_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        standard_error = '', 
                        standard_input = '', 
                        standard_output = '', 
                        start_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_start_time.v0_0_41_openapi_job_info_resp_jobs_inner_start_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        state_description = '', 
                        state_reason = '', 
                        submit_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_submit_time.v0_0_41_openapi_job_info_resp_jobs_inner_submit_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        suspend_time = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_suspend_time.v0_0_41_openapi_job_info_resp_jobs_inner_suspend_time(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        system_comment = '', 
                        tasks = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks.v0_0_41_openapi_job_info_resp_jobs_inner_tasks(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_board = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_board.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_board(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_core = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_core(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_node = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_node(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_socket = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_socket.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_socket(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tasks_per_tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_tres.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_tres(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        thread_spec = 56, 
                        threads_per_core = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_jobs_inner_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_threads_per_core(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        time_limit = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        time_minimum = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_time_minimum.v0_0_41_job_desc_msg_time_minimum(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        tres_alloc_str = '', 
                        tres_bind = '', 
                        tres_freq = '', 
                        tres_per_job = '', 
                        tres_per_node = '', 
                        tres_per_socket = '', 
                        tres_per_task = '', 
                        tres_req_str = '', 
                        user_id = 56, 
                        user_name = '', 
                        wckey = '', )
                    ],
                last_backfill = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_last_backfill.v0_0_41_openapi_job_info_resp_last_backfill(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                last_update = slurmrest_python_0_0_41.models.v0_0_41_openapi_job_info_resp_last_update.v0_0_41_openapi_job_info_resp_last_update(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
        )
        """

    def testV0041OpenapiJobInfoResp(self):
        """Test V0041OpenapiJobInfoResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
