# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_accounts_resp_accounts_inner_coordinators_inner import V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner

class TestV0041OpenapiAccountsRespAccountsInnerCoordinatorsInner(unittest.TestCase):
    """V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner:
        """Test V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner`
        """
        model = V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner()
        if include_optional:
            return V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner(
                direct = True,
                name = ''
            )
        else:
            return V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner(
                name = '',
        )
        """

    def testV0041OpenapiAccountsRespAccountsInnerCoordinatorsInner(self):
        """Test V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
