# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_job_info_resp_jobs_inner_derived_exit_code import V0041OpenapiJobInfoRespJobsInnerDerivedExitCode

class TestV0041OpenapiJobInfoRespJobsInnerDerivedExitCode(unittest.TestCase):
    """V0041OpenapiJobInfoRespJobsInnerDerivedExitCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoRespJobsInnerDerivedExitCode:
        """Test V0041OpenapiJobInfoRespJobsInnerDerivedExitCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoRespJobsInnerDerivedExitCode`
        """
        model = V0041OpenapiJobInfoRespJobsInnerDerivedExitCode()
        if include_optional:
            return V0041OpenapiJobInfoRespJobsInnerDerivedExitCode(
                return_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                signal = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                    id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    name = '', ),
                status = [
                    'INVALID'
                    ]
            )
        else:
            return V0041OpenapiJobInfoRespJobsInnerDerivedExitCode(
        )
        """

    def testV0041OpenapiJobInfoRespJobsInnerDerivedExitCode(self):
        """Test V0041OpenapiJobInfoRespJobsInnerDerivedExitCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
