# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_assocs_resp_associations_inner_max_jobs import V0041OpenapiAssocsRespAssociationsInnerMaxJobs

class TestV0041OpenapiAssocsRespAssociationsInnerMaxJobs(unittest.TestCase):
    """V0041OpenapiAssocsRespAssociationsInnerMaxJobs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsRespAssociationsInnerMaxJobs:
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxJobs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsRespAssociationsInnerMaxJobs`
        """
        model = V0041OpenapiAssocsRespAssociationsInnerMaxJobs()
        if include_optional:
            return V0041OpenapiAssocsRespAssociationsInnerMaxJobs(
                accruing = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                active = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                per = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per(
                    accruing = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_accruing.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_accruing(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    count = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    submitted = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    wall_clock = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock(
                        infinite = True, 
                        number = 56, 
                        set = True, ), ),
                total = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total(
                    infinite = True, 
                    number = 56, 
                    set = True, )
            )
        else:
            return V0041OpenapiAssocsRespAssociationsInnerMaxJobs(
        )
        """

    def testV0041OpenapiAssocsRespAssociationsInnerMaxJobs(self):
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxJobs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
