# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system import V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem

class TestV0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem:
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem`
        """
        model = V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem(
                microseconds = 56,
                seconds = 56
            )
        else:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem(
        )
        """

    def testV0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem(self):
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
