# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_accounts_resp_accounts_inner_associations_inner import V0041OpenapiAccountsRespAccountsInnerAssociationsInner

class TestV0041OpenapiAccountsRespAccountsInnerAssociationsInner(unittest.TestCase):
    """V0041OpenapiAccountsRespAccountsInnerAssociationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsRespAccountsInnerAssociationsInner:
        """Test V0041OpenapiAccountsRespAccountsInnerAssociationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsRespAccountsInnerAssociationsInner`
        """
        model = V0041OpenapiAccountsRespAccountsInnerAssociationsInner()
        if include_optional:
            return V0041OpenapiAccountsRespAccountsInnerAssociationsInner(
                account = '',
                cluster = '',
                id = 56,
                partition = '',
                user = ''
            )
        else:
            return V0041OpenapiAccountsRespAccountsInnerAssociationsInner(
                user = '',
        )
        """

    def testV0041OpenapiAccountsRespAccountsInnerAssociationsInner(self):
        """Test V0041OpenapiAccountsRespAccountsInnerAssociationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
