# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_accounts_add_cond_resp_meta_slurm_version import V0041OpenapiAccountsAddCondRespMetaSlurmVersion

class TestV0041OpenapiAccountsAddCondRespMetaSlurmVersion(unittest.TestCase):
    """V0041OpenapiAccountsAddCondRespMetaSlurmVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsAddCondRespMetaSlurmVersion:
        """Test V0041OpenapiAccountsAddCondRespMetaSlurmVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsAddCondRespMetaSlurmVersion`
        """
        model = V0041OpenapiAccountsAddCondRespMetaSlurmVersion()
        if include_optional:
            return V0041OpenapiAccountsAddCondRespMetaSlurmVersion(
                major = '',
                micro = '',
                minor = ''
            )
        else:
            return V0041OpenapiAccountsAddCondRespMetaSlurmVersion(
        )
        """

    def testV0041OpenapiAccountsAddCondRespMetaSlurmVersion(self):
        """Test V0041OpenapiAccountsAddCondRespMetaSlurmVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
