# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_kill_jobs_resp import V0041OpenapiKillJobsResp

class TestV0041OpenapiKillJobsResp(unittest.TestCase):
    """V0041OpenapiKillJobsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiKillJobsResp:
        """Test V0041OpenapiKillJobsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiKillJobsResp`
        """
        model = V0041OpenapiKillJobsResp()
        if include_optional:
            return V0041OpenapiKillJobsResp(
                errors = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_errors_inner.v0_0_41_openapi_accounts_add_cond_resp_errors_inner(
                        description = '', 
                        error = '', 
                        error_number = 56, 
                        source = '', )
                    ],
                meta = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta.v0_0_41_openapi_accounts_add_cond_resp_meta(
                    client = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_client.v0_0_41_openapi_accounts_add_cond_resp_meta_client(
                        group = '', 
                        source = '', 
                        user = '', ), 
                    command = [
                        ''
                        ], 
                    plugin = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin(
                        accounting_storage = '', 
                        data_parser = '', 
                        name = '', 
                        type = '', ), 
                    slurm = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm(
                        cluster = '', 
                        release = '', 
                        version = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), ), ),
                status = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner.v0_0_41_openapi_kill_jobs_resp_status_inner(
                        error = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_error.v0_0_41_openapi_kill_jobs_resp_status_inner_error(
                            code = 56, 
                            message = '', 
                            string = '', ), 
                        federation = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_federation.v0_0_41_openapi_kill_jobs_resp_status_inner_federation(
                            sibling = '', ), 
                        job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        step_id = '', )
                    ],
                warnings = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiKillJobsResp(
                status = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner.v0_0_41_openapi_kill_jobs_resp_status_inner(
                        error = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_error.v0_0_41_openapi_kill_jobs_resp_status_inner_error(
                            code = 56, 
                            message = '', 
                            string = '', ), 
                        federation = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_federation.v0_0_41_openapi_kill_jobs_resp_status_inner_federation(
                            sibling = '', ), 
                        job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        step_id = '', )
                    ],
        )
        """

    def testV0041OpenapiKillJobsResp(self):
        """Test V0041OpenapiKillJobsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
