# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_slurmdbd_jobs_resp import V0041OpenapiSlurmdbdJobsResp

class TestV0041OpenapiSlurmdbdJobsResp(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsResp:
        """Test V0041OpenapiSlurmdbdJobsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsResp`
        """
        model = V0041OpenapiSlurmdbdJobsResp()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsResp(
                errors = [
                    openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_errors_inner.v0_0_41_openapi_accounts_add_cond_resp_errors_inner(
                        description = '', 
                        error = '', 
                        error_number = 56, 
                        source = '', )
                    ],
                jobs = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner(
                        account = '', 
                        allocation_nodes = 56, 
                        array = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array(
                            job_id = 56, 
                            limits = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits(
                                max = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max(
                                    running = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running(
                                        tasks = 56, ), ), ), 
                            task = '', 
                            task_id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        association = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_association.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_association(
                            account = '', 
                            cluster = '', 
                            id = 56, 
                            partition = '', 
                            user = '', ), 
                        block = '', 
                        cluster = '', 
                        comment = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment(
                            administrator = '', 
                            job = '', 
                            system = '', ), 
                        constraints = '', 
                        container = '', 
                        derived_exit_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code(
                            return_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            signal = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                                id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                name = '', ), 
                            status = [
                                'INVALID'
                                ], ), 
                        exit_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code(), 
                        extra = '', 
                        failed_node = '', 
                        flags = [
                            'NONE'
                            ], 
                        group = '', 
                        het = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het(
                            job_id = 56, 
                            job_offset = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        hold = True, 
                        job_id = 56, 
                        kill_request_user = '', 
                        licenses = '', 
                        mcs = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_mcs.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_mcs(
                            label = '', ), 
                        name = '', 
                        nodes = '', 
                        partition = '', 
                        priority = openapi_client.models.v0_0_41_job_desc_msg_priority.v0_0_41_job_desc_msg_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        qos = '', 
                        required = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required(
                            cpus = 56, 
                            memory_per_cpu = openapi_client.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            memory_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        reservation = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_reservation.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_reservation(
                            name = '', ), 
                        script = '', 
                        state = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_state.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_state(
                            current = [
                                'PENDING'
                                ], 
                            reason = '', ), 
                        stderr = '', 
                        stderr_expanded = '', 
                        stdin = '', 
                        stdin_expanded = '', 
                        stdout = '', 
                        stdout_expanded = '', 
                        steps = [
                            openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner(
                                cpu = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU(
                                    governor = '', 
                                    requested_frequency = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency(
                                        min = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency_min.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency_min(
                                            infinite = True, 
                                            number = 56, 
                                            set = True, ), ), ), 
                                kill_request_user = '', 
                                nodes = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes(
                                    count = 56, 
                                    list = [
                                        ''
                                        ], 
                                    range = '', ), 
                                pid = '', 
                                statistics = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics(
                                    energy = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy(
                                        consumed = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed(
                                            infinite = True, 
                                            number = 56, 
                                            set = True, ), ), ), 
                                step = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step(
                                    name = '', ), 
                                task = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task(
                                    distribution = '', ), 
                                tasks = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks(
                                    count = 56, ), 
                                time = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time(
                                    elapsed = 56, 
                                    end = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    start = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    suspended = 56, 
                                    system = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system(
                                        microseconds = 56, 
                                        seconds = 56, ), 
                                    total = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total(
                                        microseconds = 56, 
                                        seconds = 56, ), 
                                    user = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user(
                                        microseconds = 56, 
                                        seconds = 56, ), ), 
                                tres = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres(
                                    allocated = [
                                        openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                            count = 56, 
                                            name = '', 
                                            type = '', )
                                        ], 
                                    requested = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested(
                                        average = [
                                            openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                                count = 56, 
                                                name = '', 
                                                type = '', )
                                            ], ), ), )
                            ], 
                        submit_line = '', 
                        time = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time(
                            elapsed = 56, 
                            eligible = 56, 
                            limit = openapi_client.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            planned = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            submission = 56, 
                            suspended = 56, ), 
                        tres = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres(), 
                        used_gres = '', 
                        user = '', 
                        wckey = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_wckey.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_wckey(
                            flags = [
                                'ASSIGNED_DEFAULT'
                                ], 
                            wckey = '', ), 
                        working_directory = '', )
                    ],
                meta = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta.v0_0_41_openapi_accounts_add_cond_resp_meta(
                    client = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_client.v0_0_41_openapi_accounts_add_cond_resp_meta_client(
                        group = '', 
                        source = '', 
                        user = '', ), 
                    command = [
                        ''
                        ], 
                    plugin = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin(
                        accounting_storage = '', 
                        data_parser = '', 
                        name = '', 
                        type = '', ), 
                    slurm = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm(
                        cluster = '', 
                        release = '', 
                        version = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), ), ),
                warnings = [
                    openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiSlurmdbdJobsResp(
                jobs = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner(
                        account = '', 
                        allocation_nodes = 56, 
                        array = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array(
                            job_id = 56, 
                            limits = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits(
                                max = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max(
                                    running = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running(
                                        tasks = 56, ), ), ), 
                            task = '', 
                            task_id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        association = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_association.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_association(
                            account = '', 
                            cluster = '', 
                            id = 56, 
                            partition = '', 
                            user = '', ), 
                        block = '', 
                        cluster = '', 
                        comment = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment(
                            administrator = '', 
                            job = '', 
                            system = '', ), 
                        constraints = '', 
                        container = '', 
                        derived_exit_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code(
                            return_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            signal = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                                id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                name = '', ), 
                            status = [
                                'INVALID'
                                ], ), 
                        exit_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code(), 
                        extra = '', 
                        failed_node = '', 
                        flags = [
                            'NONE'
                            ], 
                        group = '', 
                        het = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het(
                            job_id = 56, 
                            job_offset = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        hold = True, 
                        job_id = 56, 
                        kill_request_user = '', 
                        licenses = '', 
                        mcs = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_mcs.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_mcs(
                            label = '', ), 
                        name = '', 
                        nodes = '', 
                        partition = '', 
                        priority = openapi_client.models.v0_0_41_job_desc_msg_priority.v0_0_41_job_desc_msg_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        qos = '', 
                        required = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required(
                            cpus = 56, 
                            memory_per_cpu = openapi_client.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            memory_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        reservation = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_reservation.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_reservation(
                            name = '', ), 
                        script = '', 
                        state = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_state.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_state(
                            current = [
                                'PENDING'
                                ], 
                            reason = '', ), 
                        stderr = '', 
                        stderr_expanded = '', 
                        stdin = '', 
                        stdin_expanded = '', 
                        stdout = '', 
                        stdout_expanded = '', 
                        steps = [
                            openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner(
                                cpu = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU(
                                    governor = '', 
                                    requested_frequency = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency(
                                        min = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency_min.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency_min(
                                            infinite = True, 
                                            number = 56, 
                                            set = True, ), ), ), 
                                kill_request_user = '', 
                                nodes = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes(
                                    count = 56, 
                                    list = [
                                        ''
                                        ], 
                                    range = '', ), 
                                pid = '', 
                                statistics = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics(
                                    energy = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy(
                                        consumed = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed(
                                            infinite = True, 
                                            number = 56, 
                                            set = True, ), ), ), 
                                step = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step(
                                    name = '', ), 
                                task = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task(
                                    distribution = '', ), 
                                tasks = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks(
                                    count = 56, ), 
                                time = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time(
                                    elapsed = 56, 
                                    end = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    start = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    suspended = 56, 
                                    system = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system(
                                        microseconds = 56, 
                                        seconds = 56, ), 
                                    total = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total(
                                        microseconds = 56, 
                                        seconds = 56, ), 
                                    user = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user(
                                        microseconds = 56, 
                                        seconds = 56, ), ), 
                                tres = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres(
                                    allocated = [
                                        openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                            count = 56, 
                                            name = '', 
                                            type = '', )
                                        ], 
                                    requested = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested(
                                        average = [
                                            openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                                count = 56, 
                                                name = '', 
                                                type = '', )
                                            ], ), ), )
                            ], 
                        submit_line = '', 
                        time = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time(
                            elapsed = 56, 
                            eligible = 56, 
                            limit = openapi_client.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            planned = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            submission = 56, 
                            suspended = 56, ), 
                        tres = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres(), 
                        used_gres = '', 
                        user = '', 
                        wckey = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_wckey.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_wckey(
                            flags = [
                                'ASSIGNED_DEFAULT'
                                ], 
                            wckey = '', ), 
                        working_directory = '', )
                    ],
        )
        """

    def testV0041OpenapiSlurmdbdJobsResp(self):
        """Test V0041OpenapiSlurmdbdJobsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
