# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_slurmdbd_config_resp import V0041OpenapiSlurmdbdConfigResp

class TestV0041OpenapiSlurmdbdConfigResp(unittest.TestCase):
    """V0041OpenapiSlurmdbdConfigResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdConfigResp:
        """Test V0041OpenapiSlurmdbdConfigResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdConfigResp`
        """
        model = V0041OpenapiSlurmdbdConfigResp()
        if include_optional:
            return V0041OpenapiSlurmdbdConfigResp(
                accounts = [
                    openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner.v0_0_41_openapi_accounts_resp_accounts_inner(
                        associations = [
                            openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner_associations_inner.v0_0_41_openapi_accounts_resp_accounts_inner_associations_inner(
                                account = '', 
                                cluster = '', 
                                id = 56, 
                                partition = '', 
                                user = '', )
                            ], 
                        coordinators = [
                            openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_accounts_resp_accounts_inner_coordinators_inner(
                                direct = True, 
                                name = '', )
                            ], 
                        description = '', 
                        flags = [
                            'DELETED'
                            ], 
                        name = '', 
                        organization = '', )
                    ],
                associations = [
                    openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner.v0_0_41_openapi_assocs_resp_associations_inner(
                        account = '', 
                        accounting = [
                            openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner(
                                tres = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_tres.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_TRES(
                                    count = 56, 
                                    id = 56, 
                                    name = '', 
                                    type = '', ), 
                                allocated = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, )
                            ], 
                        cluster = '', 
                        comment = '', 
                        default = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_default.v0_0_41_openapi_assocs_resp_associations_inner_default(
                            qos = '', ), 
                        flags = [
                            'DELETED'
                            ], 
                        id = 56, 
                        is_default = True, 
                        lineage = '', 
                        max = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max.v0_0_41_openapi_assocs_resp_associations_inner_max(
                            jobs = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs(
                                accruing = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                active = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                per = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per(
                                    count = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    submitted = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    wall_clock = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), ), 
                                total = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), ), 
                            per = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per.v0_0_41_openapi_assocs_resp_associations_inner_max_per(
                                account = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account(), ), 
                            tres = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres.v0_0_41_openapi_assocs_resp_associations_inner_max_tres(
                                group = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_group.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_group(
                                    minutes = [
                                        openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                            id = 56, 
                                            name = '', 
                                            type = '', )
                                        ], ), 
                                minutes = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes(), ), ), 
                        min = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_min.v0_0_41_openapi_assocs_resp_associations_inner_min(
                            priority_threshold = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        parent_account = '', 
                        partition = '', 
                        priority = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_priority.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        qos = [
                            ''
                            ], 
                        shares_raw = 56, 
                        user = '', )
                    ],
                clusters = [
                    openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner.v0_0_41_openapi_clusters_resp_clusters_inner(
                        associations = openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner_associations.v0_0_41_openapi_clusters_resp_clusters_inner_associations(
                            root = openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner_associations_root.v0_0_41_openapi_clusters_resp_clusters_inner_associations_root(
                                account = '', 
                                cluster = '', 
                                id = 56, 
                                partition = '', 
                                user = '', ), ), 
                        controller = openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner_controller.v0_0_41_openapi_clusters_resp_clusters_inner_controller(
                            host = '', 
                            port = 56, ), 
                        flags = [
                            'REGISTERING'
                            ], 
                        name = '', 
                        nodes = '', 
                        rpc_version = 56, 
                        select_plugin = '', 
                        tres = [
                            openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                count = 56, 
                                id = 56, 
                                name = '', 
                                type = '', )
                            ], )
                    ],
                errors = [
                    openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_errors_inner.v0_0_41_openapi_accounts_add_cond_resp_errors_inner(
                        description = '', 
                        error = '', 
                        error_number = 56, 
                        source = '', )
                    ],
                instances = [
                    openapi_client.models.v0_0_41_openapi_instances_resp_instances_inner.v0_0_41_openapi_instances_resp_instances_inner(
                        cluster = '', 
                        extra = '', 
                        instance_id = '', 
                        instance_type = '', 
                        node_name = '', 
                        time = openapi_client.models.v0_0_41_openapi_instances_resp_instances_inner_time.v0_0_41_openapi_instances_resp_instances_inner_time(
                            time_end = 56, 
                            time_start = 56, ), )
                    ],
                meta = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta.v0_0_41_openapi_accounts_add_cond_resp_meta(
                    client = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_client.v0_0_41_openapi_accounts_add_cond_resp_meta_client(
                        group = '', 
                        source = '', 
                        user = '', ), 
                    command = [
                        ''
                        ], 
                    plugin = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin(
                        accounting_storage = '', 
                        data_parser = '', 
                        name = '', 
                        type = '', ), 
                    slurm = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm(
                        cluster = '', 
                        release = '', 
                        version = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), ), ),
                qos = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner.v0_0_41_openapi_slurmdbd_config_resp_qos_inner(
                        description = '', 
                        flags = [
                            'NOT_SET'
                            ], 
                        id = 56, 
                        limits = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits(
                            factor = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor(
                                infinite = True, 
                                number = 1.337, 
                                set = True, ), 
                            grace_time = 56, 
                            max = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max(
                                accruing = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing(
                                    per = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per(
                                        account = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account(
                                            infinite = True, 
                                            number = 56, 
                                            set = True, ), 
                                        user = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user(
                                            infinite = True, 
                                            number = 56, 
                                            set = True, ), ), ), 
                                active_jobs = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_active_jobs(
                                    count = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), ), 
                                jobs = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_jobs.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_jobs(), 
                                tres = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres(
                                    minutes = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes(), 
                                    total = [
                                        openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                            id = 56, 
                                            name = '', 
                                            type = '', )
                                        ], ), 
                                wall_clock = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock(), ), 
                            min = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_min(
                                priority_threshold = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), ), ), 
                        name = '', 
                        preempt = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt(
                            exempt_time = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt_exempt_time.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_preempt_exempt_time(
                                infinite = True, 
                                number = 56, 
                                set = True, ), 
                            list = [
                                ''
                                ], 
                            mode = [
                                'DISABLED'
                                ], ), 
                        priority = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_priority.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        usage_factor = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_factor.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_factor(
                            infinite = True, 
                            number = 1.337, 
                            set = True, ), 
                        usage_threshold = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_threshold.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_usage_threshold(
                            infinite = True, 
                            number = 1.337, 
                            set = True, ), )
                    ],
                tres = [
                    openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                        count = 56, 
                        id = 56, 
                        name = '', 
                        type = '', )
                    ],
                users = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner(
                        administrator_level = [
                            'Not Set'
                            ], 
                        associations = [
                            openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner_associations_inner.v0_0_41_openapi_accounts_resp_accounts_inner_associations_inner(
                                account = '', 
                                cluster = '', 
                                id = 56, 
                                partition = '', 
                                user = '', )
                            ], 
                        coordinators = [
                            openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_accounts_resp_accounts_inner_coordinators_inner(
                                direct = True, 
                                name = '', )
                            ], 
                        default = openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_default.v0_0_41_openapi_slurmdbd_config_resp_users_inner_default(
                            account = '', 
                            wckey = '', ), 
                        flags = [
                            'NONE'
                            ], 
                        name = '', 
                        old_name = '', 
                        wckeys = [
                            openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner(
                                accounting = [
                                    openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner(
                                        tres = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_tres.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_TRES(
                                            count = 56, 
                                            id = 56, 
                                            name = '', 
                                            type = '', ), 
                                        allocated = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated(
                                            seconds = 56, ), 
                                        id = 56, 
                                        start = 56, )
                                    ], 
                                cluster = '', 
                                id = 56, 
                                name = '', 
                                user = '', )
                            ], )
                    ],
                warnings = [
                    openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ],
                wckeys = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner.v0_0_41_openapi_slurmdbd_config_resp_users_inner_wckeys_inner(
                        accounting = [
                            openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner(
                                tres = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_tres.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_TRES(
                                    count = 56, 
                                    id = 56, 
                                    name = '', 
                                    type = '', ), 
                                allocated = openapi_client.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, )
                            ], 
                        cluster = '', 
                        flags = [
                            'DELETED'
                            ], 
                        id = 56, 
                        name = '', 
                        user = '', )
                    ]
            )
        else:
            return V0041OpenapiSlurmdbdConfigResp(
        )
        """

    def testV0041OpenapiSlurmdbdConfigResp(self):
        """Test V0041OpenapiSlurmdbdConfigResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
