# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_assocs_resp_associations_inner_max_tres_minutes import V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes

class TestV0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes(unittest.TestCase):
    """V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes:
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes`
        """
        model = V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes()
        if include_optional:
            return V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes(
                per = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes_per.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes_per(
                    job = [
                        slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                            count = 56, 
                            id = 56, 
                            name = '', 
                            type = '', )
                        ], ),
                total = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                        count = 56, 
                        id = 56, 
                        name = '', 
                        type = '', )
                    ]
            )
        else:
            return V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes(
        )
        """

    def testV0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes(self):
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxTresMinutes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
