# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_job_info_resp_jobs_inner import V0041OpenapiJobInfoRespJobsInner

class TestV0041OpenapiJobInfoRespJobsInner(unittest.TestCase):
    """V0041OpenapiJobInfoRespJobsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoRespJobsInner:
        """Test V0041OpenapiJobInfoRespJobsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoRespJobsInner`
        """
        model = V0041OpenapiJobInfoRespJobsInner()
        if include_optional:
            return V0041OpenapiJobInfoRespJobsInner(
                account = '',
                accrue_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_accrue_time.v0_0_41_openapi_job_info_resp_jobs_inner_accrue_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                admin_comment = '',
                allocating_node = '',
                array_job_id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_job_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_job_id(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                array_max_tasks = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_max_tasks.v0_0_41_openapi_job_info_resp_jobs_inner_array_max_tasks(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                array_task_id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id.v0_0_41_openapi_job_info_resp_jobs_inner_array_task_id(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                array_task_string = '',
                association_id = 56,
                batch_features = '',
                batch_flag = True,
                batch_host = '',
                billable_tres = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_billable_tres.v0_0_41_openapi_job_info_resp_jobs_inner_billable_tres(
                    infinite = True, 
                    number = 1.337, 
                    set = True, ),
                burst_buffer = '',
                burst_buffer_state = '',
                cluster = '',
                cluster_features = '',
                command = '',
                comment = '',
                container = '',
                container_id = '',
                contiguous = True,
                core_spec = 56,
                cores_per_socket = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_cores_per_socket.v0_0_41_openapi_job_info_resp_jobs_inner_cores_per_socket(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                cpu_frequency_governor = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_governor.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_governor(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                cpu_frequency_maximum = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                cpu_frequency_minimum = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum.v0_0_41_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                cpus = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_cpus(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                cpus_per_task = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_cpus_per_task.v0_0_41_openapi_job_info_resp_jobs_inner_cpus_per_task(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                cpus_per_tres = '',
                cron = '',
                current_working_directory = '',
                deadline = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_deadline.v0_0_41_openapi_job_info_resp_jobs_inner_deadline(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                delay_boot = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_delay_boot.v0_0_41_openapi_job_info_resp_jobs_inner_delay_boot(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                dependency = '',
                derived_exit_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code(
                    return_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    signal = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                        id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        name = '', ), 
                    status = [
                        'INVALID'
                        ], ),
                eligible_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_eligible_time.v0_0_41_openapi_job_info_resp_jobs_inner_eligible_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                end_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_end_time.v0_0_41_openapi_job_info_resp_jobs_inner_end_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                excluded_nodes = '',
                exclusive = [
                    'true'
                    ],
                exit_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_exit_code.v0_0_41_openapi_job_info_resp_jobs_inner_exit_code(
                    return_code = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    signal = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal(
                        id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        name = '', ), 
                    status = [
                        'INVALID'
                        ], ),
                extra = '',
                failed_node = '',
                features = '',
                federation_origin = '',
                federation_siblings_active = '',
                federation_siblings_viable = '',
                flags = [
                    'KILL_INVALID_DEPENDENCY'
                    ],
                gres_detail = [
                    ''
                    ],
                group_id = 56,
                group_name = '',
                het_job_id = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_id.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_id(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                het_job_id_set = '',
                het_job_offset = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset.v0_0_41_openapi_job_info_resp_jobs_inner_het_job_offset(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                hold = True,
                job_id = 56,
                job_resources = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(
                    cpus = 56, 
                    nodes = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(
                        allocation = [
                            openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner(
                                cpus = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus(
                                    count = 56, 
                                    used = 56, ), 
                                index = 56, 
                                memory = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(
                                    allocated = 56, 
                                    used = 56, ), 
                                name = '', 
                                sockets = [
                                    openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner(
                                        cores = [
                                            openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner(
                                                index = 56, 
                                                status = [
                                                    'INVALID'
                                                    ], )
                                            ], 
                                        index = 56, )
                                    ], )
                            ], 
                        count = 56, 
                        list = '', 
                        select_type = [
                            'AVAILABLE'
                            ], 
                        whole = True, ), 
                    select_type = [
                        'CPU'
                        ], 
                    threads_per_core = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core(
                        infinite = True, 
                        number = 56, 
                        set = True, ), ),
                job_size_str = [
                    ''
                    ],
                job_state = [
                    'PENDING'
                    ],
                last_sched_evaluation = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_last_sched_evaluation.v0_0_41_openapi_job_info_resp_jobs_inner_last_sched_evaluation(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                licenses = '',
                mail_type = [
                    'BEGIN'
                    ],
                mail_user = '',
                max_cpus = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_max_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_max_cpus(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                max_nodes = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_max_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_max_nodes(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                maximum_switch_wait_time = 56,
                mcs_label = '',
                memory_per_cpu = openapi_client.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                memory_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_memory_per_node(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                memory_per_tres = '',
                minimum_cpus_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                minimum_switches = 56,
                minimum_tmp_disk_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                name = '',
                network = '',
                nice = 56,
                node_count = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_node_count.v0_0_41_openapi_job_info_resp_jobs_inner_node_count(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                nodes = '',
                oversubscribe = True,
                partition = '',
                power = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_power.v0_0_41_openapi_job_info_resp_jobs_inner_power(
                    flags = [
                        null
                        ], ),
                pre_sus_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_pre_sus_time.v0_0_41_openapi_job_info_resp_jobs_inner_pre_sus_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                preempt_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_preempt_time.v0_0_41_openapi_job_info_resp_jobs_inner_preempt_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                preemptable_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_preemptable_time.v0_0_41_openapi_job_info_resp_jobs_inner_preemptable_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                prefer = '',
                priority = openapi_client.models.v0_0_41_job_desc_msg_priority.v0_0_41_job_desc_msg_priority(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                profile = [
                    'NOT_SET'
                    ],
                qos = '',
                reboot = True,
                requeue = True,
                required_nodes = '',
                resize_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_resize_time.v0_0_41_openapi_job_info_resp_jobs_inner_resize_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                restart_cnt = 56,
                resv_name = '',
                scheduled_nodes = '',
                selinux_context = '',
                shared = [
                    'none'
                    ],
                show_flags = [
                    'ALL'
                    ],
                sockets_per_board = 56,
                sockets_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_sockets_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_sockets_per_node(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                standard_error = '',
                standard_input = '',
                standard_output = '',
                start_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_start_time.v0_0_41_openapi_job_info_resp_jobs_inner_start_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                state_description = '',
                state_reason = '',
                submit_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_submit_time.v0_0_41_openapi_job_info_resp_jobs_inner_submit_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                suspend_time = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_suspend_time.v0_0_41_openapi_job_info_resp_jobs_inner_suspend_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                system_comment = '',
                tasks = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks.v0_0_41_openapi_job_info_resp_jobs_inner_tasks(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tasks_per_board = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_board.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_board(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tasks_per_core = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_core(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tasks_per_node = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_node.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_node(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tasks_per_socket = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_socket.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_socket(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tasks_per_tres = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_tres.v0_0_41_openapi_job_info_resp_jobs_inner_tasks_per_tres(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                thread_spec = 56,
                threads_per_core = openapi_client.models.v0_0_41_openapi_job_info_resp_jobs_inner_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_threads_per_core(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                time_limit = openapi_client.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                time_minimum = openapi_client.models.v0_0_41_job_desc_msg_time_minimum.v0_0_41_job_desc_msg_time_minimum(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tres_alloc_str = '',
                tres_bind = '',
                tres_freq = '',
                tres_per_job = '',
                tres_per_node = '',
                tres_per_socket = '',
                tres_per_task = '',
                tres_req_str = '',
                user_id = 56,
                user_name = '',
                wckey = ''
            )
        else:
            return V0041OpenapiJobInfoRespJobsInner(
        )
        """

    def testV0041OpenapiJobInfoRespJobsInner(self):
        """Test V0041OpenapiJobInfoRespJobsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
