# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_assocs_resp_associations_inner_max_jobs_total import V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal

class TestV0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal(unittest.TestCase):
    """V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal:
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal`
        """
        model = V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal()
        if include_optional:
            return V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal(
                infinite = True,
                number = 56,
                set = True
            )
        else:
            return V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal(
        )
        """

    def testV0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal(self):
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxJobsTotal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
