# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_assocs_resp_associations_inner_max_jobs_per import V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer

class TestV0041OpenapiAssocsRespAssociationsInnerMaxJobsPer(unittest.TestCase):
    """V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer:
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer`
        """
        model = V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer()
        if include_optional:
            return V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer(
                accruing = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_accruing.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_accruing(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                count = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                submitted = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                wall_clock = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock(
                    infinite = True, 
                    number = 56, 
                    set = True, )
            )
        else:
            return V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer(
        )
        """

    def testV0041OpenapiAssocsRespAssociationsInnerMaxJobsPer(self):
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxJobsPer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
