# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_clusters_resp_clusters_inner import V0041OpenapiClustersRespClustersInner

class TestV0041OpenapiClustersRespClustersInner(unittest.TestCase):
    """V0041OpenapiClustersRespClustersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiClustersRespClustersInner:
        """Test V0041OpenapiClustersRespClustersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiClustersRespClustersInner`
        """
        model = V0041OpenapiClustersRespClustersInner()
        if include_optional:
            return V0041OpenapiClustersRespClustersInner(
                associations = openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner_associations.v0_0_41_openapi_clusters_resp_clusters_inner_associations(
                    root = openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner_associations_root.v0_0_41_openapi_clusters_resp_clusters_inner_associations_root(
                        account = '', 
                        cluster = '', 
                        id = 56, 
                        partition = '', 
                        user = '', ), ),
                controller = openapi_client.models.v0_0_41_openapi_clusters_resp_clusters_inner_controller.v0_0_41_openapi_clusters_resp_clusters_inner_controller(
                    host = '', 
                    port = 56, ),
                flags = [
                    'REGISTERING'
                    ],
                name = '',
                nodes = '',
                rpc_version = 56,
                select_plugin = '',
                tres = [
                    openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                        count = 56, 
                        id = 56, 
                        name = '', 
                        type = '', )
                    ]
            )
        else:
            return V0041OpenapiClustersRespClustersInner(
        )
        """

    def testV0041OpenapiClustersRespClustersInner(self):
        """Test V0041OpenapiClustersRespClustersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
