# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_kill_jobs_resp_status_inner import V0041OpenapiKillJobsRespStatusInner

class TestV0041OpenapiKillJobsRespStatusInner(unittest.TestCase):
    """V0041OpenapiKillJobsRespStatusInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiKillJobsRespStatusInner:
        """Test V0041OpenapiKillJobsRespStatusInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiKillJobsRespStatusInner`
        """
        model = V0041OpenapiKillJobsRespStatusInner()
        if include_optional:
            return V0041OpenapiKillJobsRespStatusInner(
                error = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_error.v0_0_41_openapi_kill_jobs_resp_status_inner_error(
                    code = 56, 
                    message = '', 
                    string = '', ),
                federation = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_federation.v0_0_41_openapi_kill_jobs_resp_status_inner_federation(
                    sibling = '', ),
                job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                step_id = ''
            )
        else:
            return V0041OpenapiKillJobsRespStatusInner(
                job_id = slurmrest_python_0_0_41.models.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id.v0_0_41_openapi_kill_jobs_resp_status_inner_job_id(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                step_id = '',
        )
        """

    def testV0041OpenapiKillJobsRespStatusInner(self):
        """Test V0041OpenapiKillJobsRespStatusInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
