# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_instances_resp_instances_inner import V0041OpenapiInstancesRespInstancesInner

class TestV0041OpenapiInstancesRespInstancesInner(unittest.TestCase):
    """V0041OpenapiInstancesRespInstancesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiInstancesRespInstancesInner:
        """Test V0041OpenapiInstancesRespInstancesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiInstancesRespInstancesInner`
        """
        model = V0041OpenapiInstancesRespInstancesInner()
        if include_optional:
            return V0041OpenapiInstancesRespInstancesInner(
                cluster = '',
                extra = '',
                instance_id = '',
                instance_type = '',
                node_name = '',
                time = slurmrest_python_0_0_41.models.v0_0_41_openapi_instances_resp_instances_inner_time.v0_0_41_openapi_instances_resp_instances_inner_time(
                    time_end = 56, 
                    time_start = 56, )
            )
        else:
            return V0041OpenapiInstancesRespInstancesInner(
        )
        """

    def testV0041OpenapiInstancesRespInstancesInner(self):
        """Test V0041OpenapiInstancesRespInstancesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
