# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_assocs_resp import V0041OpenapiAssocsResp

class TestV0041OpenapiAssocsResp(unittest.TestCase):
    """V0041OpenapiAssocsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsResp:
        """Test V0041OpenapiAssocsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsResp`
        """
        model = V0041OpenapiAssocsResp()
        if include_optional:
            return V0041OpenapiAssocsResp(
                associations = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner.v0_0_41_openapi_assocs_resp_associations_inner(
                        account = '', 
                        accounting = [
                            slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner(
                                tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_tres.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_TRES(
                                    count = 56, 
                                    id = 56, 
                                    name = '', 
                                    type = '', ), 
                                allocated = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, )
                            ], 
                        cluster = '', 
                        comment = '', 
                        default = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_default.v0_0_41_openapi_assocs_resp_associations_inner_default(
                            qos = '', ), 
                        flags = [
                            'DELETED'
                            ], 
                        id = 56, 
                        is_default = True, 
                        lineage = '', 
                        max = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max.v0_0_41_openapi_assocs_resp_associations_inner_max(
                            jobs = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs(
                                accruing = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                active = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                per = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per(
                                    count = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    submitted = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    wall_clock = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), ), 
                                total = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), ), 
                            per = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per.v0_0_41_openapi_assocs_resp_associations_inner_max_per(
                                account = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account(), ), 
                            tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres.v0_0_41_openapi_assocs_resp_associations_inner_max_tres(
                                group = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_group.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_group(
                                    minutes = [
                                        slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                            id = 56, 
                                            name = '', 
                                            type = '', )
                                        ], ), 
                                minutes = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes(), ), ), 
                        min = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_min.v0_0_41_openapi_assocs_resp_associations_inner_min(
                            priority_threshold = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        parent_account = '', 
                        partition = '', 
                        priority = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_priority.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        qos = [
                            ''
                            ], 
                        shares_raw = 56, 
                        user = '', )
                    ],
                errors = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_errors_inner.v0_0_41_openapi_accounts_add_cond_resp_errors_inner(
                        description = '', 
                        error = '', 
                        error_number = 56, 
                        source = '', )
                    ],
                meta = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta.v0_0_41_openapi_accounts_add_cond_resp_meta(
                    client = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_client.v0_0_41_openapi_accounts_add_cond_resp_meta_client(
                        group = '', 
                        source = '', 
                        user = '', ), 
                    command = [
                        ''
                        ], 
                    plugin = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin(
                        accounting_storage = '', 
                        data_parser = '', 
                        name = '', 
                        type = '', ), 
                    slurm = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm(
                        cluster = '', 
                        release = '', 
                        version = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), ), ),
                warnings = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner.v0_0_41_openapi_accounts_add_cond_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiAssocsResp(
                associations = [
                    slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner.v0_0_41_openapi_assocs_resp_associations_inner(
                        account = '', 
                        accounting = [
                            slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner(
                                tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_tres.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_TRES(
                                    count = 56, 
                                    id = 56, 
                                    name = '', 
                                    type = '', ), 
                                allocated = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated.v0_0_41_openapi_assocs_resp_associations_inner_accounting_inner_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, )
                            ], 
                        cluster = '', 
                        comment = '', 
                        default = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_default.v0_0_41_openapi_assocs_resp_associations_inner_default(
                            qos = '', ), 
                        flags = [
                            'DELETED'
                            ], 
                        id = 56, 
                        is_default = True, 
                        lineage = '', 
                        max = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max.v0_0_41_openapi_assocs_resp_associations_inner_max(
                            jobs = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs(
                                accruing = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_accruing(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                active = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_active(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), 
                                per = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per(
                                    count = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_count(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    submitted = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_submitted(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), 
                                    wall_clock = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_per_wall_clock(
                                        infinite = True, 
                                        number = 56, 
                                        set = True, ), ), 
                                total = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total.v0_0_41_openapi_assocs_resp_associations_inner_max_jobs_total(
                                    infinite = True, 
                                    number = 56, 
                                    set = True, ), ), 
                            per = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per.v0_0_41_openapi_assocs_resp_associations_inner_max_per(
                                account = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account(), ), 
                            tres = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres.v0_0_41_openapi_assocs_resp_associations_inner_max_tres(
                                group = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_group.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_group(
                                    minutes = [
                                        slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner(
                                            id = 56, 
                                            name = '', 
                                            type = '', )
                                        ], ), 
                                minutes = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes.v0_0_41_openapi_assocs_resp_associations_inner_max_tres_minutes(), ), ), 
                        min = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_min.v0_0_41_openapi_assocs_resp_associations_inner_min(
                            priority_threshold = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold.v0_0_41_openapi_assocs_resp_associations_inner_min_priority_threshold(
                                infinite = True, 
                                number = 56, 
                                set = True, ), ), 
                        parent_account = '', 
                        partition = '', 
                        priority = slurmrest_python_0_0_41.models.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_priority.v0_0_41_openapi_accounts_add_cond_resp_association_condition_association_priority(
                            infinite = True, 
                            number = 56, 
                            set = True, ), 
                        qos = [
                            ''
                            ], 
                        shares_raw = 56, 
                        user = '', )
                    ],
        )
        """

    def testV0041OpenapiAssocsResp(self):
        """Test V0041OpenapiAssocsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
