# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_accounts_add_cond_resp_association_condition_association_grptres_inner import V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner

class TestV0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner(unittest.TestCase):
    """V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner:
        """Test V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner`
        """
        model = V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner()
        if include_optional:
            return V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner(
                count = 56,
                id = 56,
                name = '',
                type = ''
            )
        else:
            return V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner(
                type = '',
        )
        """

    def testV0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner(self):
        """Test V0041OpenapiAccountsAddCondRespAssociationConditionAssociationGrptresInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
