# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_job_desc_msg import V0041JobDescMsg

class TestV0041JobDescMsg(unittest.TestCase):
    """V0041JobDescMsg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041JobDescMsg:
        """Test V0041JobDescMsg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041JobDescMsg`
        """
        model = V0041JobDescMsg()
        if include_optional:
            return V0041JobDescMsg(
                account = '',
                account_gather_frequency = '',
                admin_comment = '',
                allocation_node_list = '',
                allocation_node_port = 56,
                argv = [
                    ''
                    ],
                array = '',
                batch_features = '',
                begin_time = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_begin_time.v0_0_41_job_desc_msg_begin_time(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                burst_buffer = '',
                cluster_constraint = '',
                clusters = '',
                comment = '',
                constraints = '',
                container = '',
                container_id = '',
                contiguous = True,
                core_specification = 56,
                cpu_binding = '',
                cpu_binding_flags = [
                    'CPU_BIND_TO_THREADS'
                    ],
                cpu_frequency = '',
                cpus_per_task = 56,
                cpus_per_tres = '',
                crontab = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_crontab.v0_0_41_job_desc_msg_crontab(
                    command = '', 
                    day_of_month = '', 
                    day_of_week = '', 
                    flags = [
                        'WILD_MINUTE'
                        ], 
                    hour = '', 
                    line = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_crontab_line.v0_0_41_job_desc_msg_crontab_line(
                        end = 56, 
                        start = 56, ), 
                    minute = '', 
                    month = '', 
                    specification = '', ),
                current_working_directory = '',
                deadline = 56,
                delay_boot = 56,
                dependency = '',
                distribution = '',
                distribution_plane_size = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_distribution_plane_size.v0_0_41_job_desc_msg_distribution_plane_size(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                end_time = 56,
                environment = [
                    ''
                    ],
                excluded_nodes = [
                    ''
                    ],
                exclusive = [
                    'true'
                    ],
                extra = '',
                flags = [
                    'KILL_INVALID_DEPENDENCY'
                    ],
                group_id = '',
                hetjob_group = 56,
                hold = True,
                immediate = True,
                job_id = 56,
                kill_on_node_fail = True,
                kill_warning_delay = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_kill_warning_delay.v0_0_41_job_desc_msg_kill_warning_delay(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                kill_warning_flags = [
                    'BATCH_JOB'
                    ],
                kill_warning_signal = '',
                licenses = '',
                mail_type = [
                    'BEGIN'
                    ],
                mail_user = '',
                maximum_cpus = 56,
                maximum_nodes = 56,
                mcs_label = '',
                memory_binding = '',
                memory_binding_type = [
                    'NONE'
                    ],
                memory_per_cpu = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                memory_per_node = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_memory_per_cpu.v0_0_41_job_desc_msg_memory_per_cpu(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                memory_per_tres = '',
                minimum_boards_per_node = 56,
                minimum_cpus = 56,
                minimum_cpus_per_node = 56,
                minimum_nodes = 56,
                minimum_sockets_per_board = 56,
                name = '',
                network = '',
                nice = 56,
                nodes = '',
                ntasks_per_tres = 56,
                open_mode = [
                    'APPEND'
                    ],
                overcommit = True,
                oversubscribe = True,
                partition = '',
                power_flags = [
                    null
                    ],
                prefer = '',
                priority = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_priority.v0_0_41_job_desc_msg_priority(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                profile = [
                    'NOT_SET'
                    ],
                qos = '',
                reboot = True,
                requeue = True,
                required_nodes = [
                    ''
                    ],
                required_switches = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_required_switches.v0_0_41_job_desc_msg_required_switches(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                reservation = '',
                reserve_ports = 56,
                resv_mpi_ports = 56,
                rlimits = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits.v0_0_41_job_desc_msg_rlimits(
                    as = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_as.v0_0_41_job_desc_msg_rlimits_as(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    core = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_core.v0_0_41_job_desc_msg_rlimits_core(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    cpu = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_cpu.v0_0_41_job_desc_msg_rlimits_cpu(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    data = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_data.v0_0_41_job_desc_msg_rlimits_data(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    fsize = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_fsize.v0_0_41_job_desc_msg_rlimits_fsize(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    memlock = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_memlock.v0_0_41_job_desc_msg_rlimits_memlock(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    nofile = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_nofile.v0_0_41_job_desc_msg_rlimits_nofile(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    nproc = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_nproc.v0_0_41_job_desc_msg_rlimits_nproc(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    rss = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_rss.v0_0_41_job_desc_msg_rlimits_rss(
                        infinite = True, 
                        number = 56, 
                        set = True, ), 
                    stack = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_rlimits_stack.v0_0_41_job_desc_msg_rlimits_stack(
                        infinite = True, 
                        number = 56, 
                        set = True, ), ),
                script = '',
                segment_size = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_segment_size.v0_0_41_job_desc_msg_segment_size(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                selinux_context = '',
                shared = [
                    'none'
                    ],
                site_factor = 56,
                sockets_per_node = 56,
                spank_environment = [
                    ''
                    ],
                standard_error = '',
                standard_input = '',
                standard_output = '',
                tasks = 56,
                tasks_per_board = 56,
                tasks_per_core = 56,
                tasks_per_node = 56,
                tasks_per_socket = 56,
                temporary_disk_per_node = 56,
                thread_specification = 56,
                threads_per_core = 56,
                time_limit = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                time_minimum = slurmrest_python_0_0_41.models.v0_0_41_job_desc_msg_time_minimum.v0_0_41_job_desc_msg_time_minimum(
                    infinite = True, 
                    number = 56, 
                    set = True, ),
                tres_bind = '',
                tres_freq = '',
                tres_per_job = '',
                tres_per_node = '',
                tres_per_socket = '',
                tres_per_task = '',
                user_id = '',
                wait_all_nodes = True,
                wait_for_switch = 56,
                wckey = '',
                x11 = [
                    'FORWARD_ALL_NODES'
                    ],
                x11_magic_cookie = '',
                x11_target_host = '',
                x11_target_port = 56
            )
        else:
            return V0041JobDescMsg(
        )
        """

    def testV0041JobDescMsg(self):
        """Test V0041JobDescMsg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
