# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrest_python_0_0_41.models.v0041_openapi_assocs_resp_associations_inner_max_per import V0041OpenapiAssocsRespAssociationsInnerMaxPer

class TestV0041OpenapiAssocsRespAssociationsInnerMaxPer(unittest.TestCase):
    """V0041OpenapiAssocsRespAssociationsInnerMaxPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAssocsRespAssociationsInnerMaxPer:
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxPer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAssocsRespAssociationsInnerMaxPer`
        """
        model = V0041OpenapiAssocsRespAssociationsInnerMaxPer()
        if include_optional:
            return V0041OpenapiAssocsRespAssociationsInnerMaxPer(
                account = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account(
                    wall_clock = slurmrest_python_0_0_41.models.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account_wall_clock.v0_0_41_openapi_assocs_resp_associations_inner_max_per_account_wall_clock(
                        infinite = True, 
                        number = 56, 
                        set = True, ), )
            )
        else:
            return V0041OpenapiAssocsRespAssociationsInnerMaxPer(
        )
        """

    def testV0041OpenapiAssocsRespAssociationsInnerMaxPer(self):
        """Test V0041OpenapiAssocsRespAssociationsInnerMaxPer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
