# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_accounts_resp_accounts_inner import V0041OpenapiAccountsRespAccountsInner

class TestV0041OpenapiAccountsRespAccountsInner(unittest.TestCase):
    """V0041OpenapiAccountsRespAccountsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsRespAccountsInner:
        """Test V0041OpenapiAccountsRespAccountsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsRespAccountsInner`
        """
        model = V0041OpenapiAccountsRespAccountsInner()
        if include_optional:
            return V0041OpenapiAccountsRespAccountsInner(
                associations = [
                    openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner_associations_inner.v0_0_41_openapi_accounts_resp_accounts_inner_associations_inner(
                        account = '', 
                        cluster = '', 
                        id = 56, 
                        partition = '', 
                        user = '', )
                    ],
                coordinators = [
                    openapi_client.models.v0_0_41_openapi_accounts_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_accounts_resp_accounts_inner_coordinators_inner(
                        direct = True, 
                        name = '', )
                    ],
                description = '',
                flags = [
                    'DELETED'
                    ],
                name = '',
                organization = ''
            )
        else:
            return V0041OpenapiAccountsRespAccountsInner(
                description = '',
                name = '',
                organization = '',
        )
        """

    def testV0041OpenapiAccountsRespAccountsInner(self):
        """Test V0041OpenapiAccountsRespAccountsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
