# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_accounts_add_cond_resp_meta import V0041OpenapiAccountsAddCondRespMeta

class TestV0041OpenapiAccountsAddCondRespMeta(unittest.TestCase):
    """V0041OpenapiAccountsAddCondRespMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsAddCondRespMeta:
        """Test V0041OpenapiAccountsAddCondRespMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsAddCondRespMeta`
        """
        model = V0041OpenapiAccountsAddCondRespMeta()
        if include_optional:
            return V0041OpenapiAccountsAddCondRespMeta(
                client = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_client.v0_0_41_openapi_accounts_add_cond_resp_meta_client(
                    group = '', 
                    source = '', 
                    user = '', ),
                command = [
                    ''
                    ],
                plugin = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin.v0_0_41_openapi_accounts_add_cond_resp_meta_plugin(
                    accounting_storage = '', 
                    data_parser = '', 
                    name = '', 
                    type = '', ),
                slurm = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm(
                    cluster = '', 
                    release = '', 
                    version = openapi_client.models.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version.v0_0_41_openapi_accounts_add_cond_resp_meta_slurm_version(
                        major = '', 
                        micro = '', 
                        minor = '', ), )
            )
        else:
            return V0041OpenapiAccountsAddCondRespMeta(
        )
        """

    def testV0041OpenapiAccountsAddCondRespMeta(self):
        """Test V0041OpenapiAccountsAddCondRespMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
