# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.11.5&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_slurmdbd_stats_resp_statistics_rpcs_inner import V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner

class TestV0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner(unittest.TestCase):
    """V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner:
        """Test V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner`
        """
        model = V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner()
        if include_optional:
            return V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner(
                count = 56,
                rpc = '',
                time = openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rpcs_inner_time.v0_0_41_openapi_slurmdbd_stats_resp_statistics_RPCs_inner_time(
                    average = 56, 
                    total = 56, )
            )
        else:
            return V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner(
        )
        """

    def testV0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner(self):
        """Test V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
